services:
  client:
    container_name: secret-kiss-client
    image: client:1.0.0
    build:
      context: ./client
      dockerfile: client.dockerfile
    ports:
      - 5173:5173
    depends_on:
      - server
  server:
    container_name: secret-kiss-server
    image: server:1.0.0
    build:
      context: ./server
      dockerfile: server.dockerfile
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    container_name: secret-kiss-database
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
